### ISSUE TITLE
Deploy PokeMe to AVAX, BSC and Arbitrum

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/poke-me#24]
Deploy PokeMe smart contracts and verify them on: 

- [x] Avax
- [x] Bsc
- [x] Arbitrum

**Comment by hilmarx** [comment]
LGTM

**Comment by Matthews3301** [comment]
@brandonchuah For Arbitrum, what are the addresses of:

```
pokeme
pokemeV3
treasury
forwarder
```
?

**Comment by brandonchuah** [comment]
- Forwarder : `0x95f4538C3950CE0EF5821f2049aE2aC5cCade68D`
